# Generated by Django 5.0.1 on 2024-03-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_screen', '0002_rename_address_meter_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('text', models.FloatField()),
            ],
        ),
    ]
