# Generated by Django 5.0.1 on 2024-04-05 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_screen', '0004_waterunit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WaterUnit',
        ),
    ]
