# Generated by Django 5.0.1 on 2024-04-06 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_screen', '0004_waterunit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WaterUnit',
            new_name='PrepaymentOption',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('confirmation_code', models.CharField(max_length=20)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_screen.prepaymentoption')),
            ],
        ),
    ]
