# Generated by Django 5.0.1 on 2024-04-24 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_screen', '0004_prepaymentoption_waterpurchasetransaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='selected_option',
        ),
        migrations.DeleteModel(
            name='PrepaymentOption',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
