# Generated by Django 4.2.12 on 2024-05-08 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home_screen', '0005_remove_transaction_selected_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter_data',
            name='meter_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home_screen.meter_address'),
        ),
    ]
