# Generated by Django 4.2.12 on 2024-05-14 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home_screen', '0007_meter_address_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterpurchasetransaction',
            name='meter_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home_screen.meter_address'),
        ),
        migrations.AddField(
            model_name='waterpurchasetransaction',
            name='user_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='waterpurchasetransaction',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='waterpurchasetransaction',
            name='liters_purchased',
            field=models.FloatField(default=0),
        ),
    ]
