# Generated by Django 4.2.12 on 2024-05-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_screen', '0008_waterpurchasetransaction_meter_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meter_data',
            name='text',
        ),
        migrations.AddField(
            model_name='meter_data',
            name='flowRate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meter_data',
            name='totalLiters',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meter_data',
            name='totalLitersLeft',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meter_data',
            name='totalMilli',
            field=models.FloatField(default=0),
        ),
    ]
